# permissions for end users to view sharedconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sharedconfig-viewer-role
rules:
- apiGroups:
  - config.devops.prasad.com
  resources:
  - sharedconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - config.devops.prasad.com
  resources:
  - sharedconfigs/status
  verbs:
  - get
